name: pokedex
description: pokedex app
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  pk_shared:
    path: ../pk_shared
  pk_http_client:
    path: ../pk_http_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.3
  bloc_test: 9.1.7
  build_runner: 2.4.9
  flutter_lints: 4.0.0
  flutter_native_splash: 2.4.0

flutter:
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400

  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  image: "assets/images/splash_logo.png"
  color: "#3558CD"
